teams:
  viz:
    channel: "visuals-graphics"
    ga_org_id: "100688391"
  carebot:
    channel: "carebot-dev"
    ga_org_id: "118286276"
sources:
  -
    team: "viz"
    type: "spreadsheet"
    doc_key: "1Gcumd0uOl3eSUvc0y5CWmmHVOKwX609-js5EnE8i3lI"
  -
    team: "carebot"
    type: "rss"
    url: "https://thecarebot.github.io/feed.xml"
    date_field: 'published'
    url_field: 'id'
    title_fied: 'title'

