teams:
  default:
    channel: "visuals-graphics"
    ga_org_id: "123456789"
  viz:
    channel: "visuals-graphics"
    ga_org_id: '123456789'
  carebot:
    channel: "carebot-dev"
    ga_org_id: '123456789'
sources:
  -
    team: "viz"
    type: "spreadsheet"
    doc_key: "spreadhseet-doc-key"
    article_id:
  -
    team: "carebot"
    type: "rss"
    url: "https://thecarebot.github.io/feed.xml"

