teams:
  default:
    channel: "visuals-graphics"
    ga_org_id: "1234"
  viz:
    channel: "visuals-graphics"
    ga_org_id: '1234'
  carebot:
    channel: "carebot-dev"
    ga_org_id: '5678'
sources:
  -
    team: "viz"
    type: "spreadsheet"
    doc_key: "spreadhseet-doc-key"
  -
    team: "carebot"
    type: "rss"
    url: "https://thecarebot.github.io/feed.xml"

