teams:
  viz:
    channel: "visuals-graphics"
  carebot:
    channel: "carebot-dev"
sources:
  -
    team: "viz"
    type: "spreadsheet"
    doc_key: "spreadhseet-doc-key"
  -
    team: "carebot"
    type: "rss"
    url: "https://thecarebot.github.io/feed.xml"

